/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaapp;
;

import Contacto.Contacto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author anthoro
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, 343, 630);
        setLocationRelativeTo(null);
        //OCULTAMIENTO
        bt_guardar.setOpaque(false);
        bt_guardar.setContentAreaFilled(false);
        bt_selecfoto.setOpaque(false);
        bt_selecfoto.setContentAreaFilled(false);
        bt_submenuverde.setOpaque(false);
        bt_submenuverde.setContentAreaFilled(false);
        bt_volver.setOpaque(false);
        bt_volver.setContentAreaFilled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_volver = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_submenuverde = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();
        bt_selecfoto = new javax.swing.JButton();
        tf_nota = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_telefono = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        cb_sexo = new javax.swing.JComboBox<>();
        cb_grupo = new javax.swing.JComboBox<>();
        lb_grupo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_error3 = new javax.swing.JLabel();
        lb_error1 = new javax.swing.JLabel();
        lb_error2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        getContentPane().add(bt_volver);
        bt_volver.setBounds(10, 10, 50, 30);

        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_guardar);
        bt_guardar.setBounds(250, 0, 40, 40);

        bt_submenuverde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submenuverdeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_submenuverde);
        bt_submenuverde.setBounds(320, 10, 20, 30);

        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contacto/contacts-32.png"))); // NOI18N
        getContentPane().add(lb_foto);
        lb_foto.setBounds(20, 90, 80, 100);

        bt_selecfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selecfotoActionPerformed(evt);
            }
        });
        getContentPane().add(bt_selecfoto);
        bt_selecfoto.setBounds(40, 200, 40, 30);

        tf_nota.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tf_nota.setForeground(new java.awt.Color(132, 132, 132));
        tf_nota.setText("Nota...");
        tf_nota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tf_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_notaMouseClicked(evt);
            }
        });
        tf_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_notaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nota);
        tf_nota.setBounds(40, 470, 270, 30);

        tf_nombre.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tf_nombre.setForeground(new java.awt.Color(132, 132, 132));
        tf_nombre.setText("Nombre:");
        tf_nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tf_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_nombreMouseClicked(evt);
            }
        });
        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });
        tf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(tf_nombre);
        tf_nombre.setBounds(130, 90, 180, 30);

        tf_telefono.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tf_telefono.setForeground(new java.awt.Color(132, 132, 132));
        tf_telefono.setText("Telefono:");
        tf_telefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tf_telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_telefonoMouseClicked(evt);
            }
        });
        tf_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(tf_telefono);
        tf_telefono.setBounds(40, 240, 260, 30);

        tf_apellido.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tf_apellido.setForeground(new java.awt.Color(132, 132, 132));
        tf_apellido.setText("Apellido:");
        tf_apellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tf_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_apellidoMouseClicked(evt);
            }
        });
        tf_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_apellidoKeyTyped(evt);
            }
        });
        getContentPane().add(tf_apellido);
        tf_apellido.setBounds(130, 160, 180, 30);

        cb_sexo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "femenino", "masculino" }));
        cb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_sexo);
        cb_sexo.setBounds(90, 320, 220, 30);

        cb_grupo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Amigos", "Familia", "Colegas", "Escuela", "Otros" }));
        getContentPane().add(cb_grupo);
        cb_grupo.setBounds(100, 390, 210, 30);

        lb_grupo.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        lb_grupo.setText("Grupo:");
        getContentPane().add(lb_grupo);
        lb_grupo.setBounds(40, 390, 50, 30);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 320, 40, 30);

        lb_error3.setForeground(new java.awt.Color(255, 0, 0));
        lb_error3.setText("No se han ingresado valores");
        getContentPane().add(lb_error3);
        lb_error3.setBounds(30, 280, 200, 20);

        lb_error1.setForeground(new java.awt.Color(255, 0, 0));
        lb_error1.setText("No se han ingresado valores");
        getContentPane().add(lb_error1);
        lb_error1.setBounds(120, 130, 200, 20);

        lb_error2.setForeground(new java.awt.Color(255, 0, 0));
        lb_error2.setText("No se han ingresado valores");
        getContentPane().add(lb_error2);
        lb_error2.setBounds(120, 200, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaapp/imagenes/bg_agregar.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        // TODO add your handling code here:
        Menu menu1 = new Menu();
        setVisible(false);
        menu1.setVisible(true);
        
    }//GEN-LAST:event_bt_volverActionPerformed

    private void bt_selecfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_selecfotoActionPerformed
        // TODO add your handling code here:
        JFileChooser seleccion=new JFileChooser();//activa la seleccion de la foto
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivo imagen","jpg");
        seleccion.setFileFilter(filtro);
        int ind=seleccion.showDialog(this, "Seleccione la imagen");
        if(ind==0){
            String ruta=seleccion.getSelectedFile().getAbsolutePath();
            lb_foto.setIcon(new ImageIcon(ruta));
            //conbertir la imagen a icono
            ImageIcon icon=new ImageIcon(ruta);
            //modificar el icono para darle formato
            Image img=icon.getImage();
            Image newimg=img.getScaledInstance(84, 110, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newicon=new ImageIcon(newimg);
            lb_foto.setIcon(newicon);
            lb_foto.setSize(84,110);
            lb_foto.setText(ruta);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione su foto");
        }
    }//GEN-LAST:event_bt_selecfotoActionPerformed

    private void cb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sexoActionPerformed

    private void tf_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_notaActionPerformed

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void tf_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_nombreMouseClicked
        // TODO add your handling code here:
        
        tf_nombre.setText("");
    }//GEN-LAST:event_tf_nombreMouseClicked

    private void tf_apellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_apellidoMouseClicked
        // TODO add your handling code here:
        tf_apellido.setText("");
    }//GEN-LAST:event_tf_apellidoMouseClicked

    private void tf_telefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_telefonoMouseClicked
        // TODO add your handling code here:
        tf_telefono.setText("");
    }//GEN-LAST:event_tf_telefonoMouseClicked

    private void tf_notaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_notaMouseClicked
        // TODO add your handling code here:
        tf_nota.setText("");
    }//GEN-LAST:event_tf_notaMouseClicked

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
        if(tf_nombre.getText().isEmpty()||tf_apellido.getText().isEmpty()||tf_telefono.getText().isEmpty()
                ||cb_grupo.getSelectedItem().toString() == "Seleccione..." || 
                cb_sexo.getSelectedItem().toString() == "Seleccione...")
            JOptionPane.showMessageDialog(null, "Los campos no han sido llenados", "Error", JOptionPane.WARNING_MESSAGE);
        else
            if(tf_telefono.getText().toString().length()!=10)
                JOptionPane.showMessageDialog(null, "El numero de telefono no cumple con los 10 digitos ", "Error", JOptionPane.WARNING_MESSAGE);
            else{
                JOptionPane.showMessageDialog(null, "Ingreso satisfactorio", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
                //CREO EL OBJETOCO CONTACTO
                Contacto contact = new Contacto();
                contact.setNombre(tf_nombre.getText().toString());
                contact.setApellido(tf_apellido.getText().toString());
                contact.setGrupo(cb_grupo.getSelectedItem().toString());
                contact.setNumero(tf_telefono.getText().toString());
                contact.setSexo(cb_sexo.getSelectedItem().toString());
                contact.setNota(tf_nota.getText().toString());
                
                bt_volverActionPerformed(evt);
                
                
            }
                    
    }//GEN-LAST:event_bt_guardarActionPerformed
     
    private void tf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c))
        {
            getToolkit().beep();
            evt.consume(); 
        }
        else
            lb_error1.setVisible(false);
    }//GEN-LAST:event_tf_nombreKeyTyped

    private void tf_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_apellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c))
        {
            getToolkit().beep();
            evt.consume(); 
        }   
        else
            lb_error2.setVisible(false);
    }//GEN-LAST:event_tf_apellidoKeyTyped

    private void tf_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_telefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume(); 
        }   
        else
            lb_error3.setVisible(false);
    }//GEN-LAST:event_tf_telefonoKeyTyped

    private void bt_submenuverdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submenuverdeActionPerformed
        // TODO add your handling code here:
        Submenuverde submv1 = new Submenuverde();
        submv1.setVisible(true);
    }//GEN-LAST:event_bt_submenuverdeActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_selecfoto;
    private javax.swing.JButton bt_submenuverde;
    private javax.swing.JButton bt_volver;
    private javax.swing.JComboBox<String> cb_grupo;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_error1;
    private javax.swing.JLabel lb_error2;
    private javax.swing.JLabel lb_error3;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_grupo;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nota;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables
}
