/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaapp;

import java.awt.*;

/**
 *
 * @author rayo
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(1,1, 363,654);
        setLocationRelativeTo(null);
        bt_volver.setOpaque(false);
        bt_volver.setContentAreaFilled(false);
        bt_compartir.setOpaque(false);
        bt_compartir.setContentAreaFilled(false);
        bt_editar.setOpaque(false);
        bt_editar.setContentAreaFilled(false);
        bt_submenuverde.setOpaque(false);
        bt_submenuverde.setContentAreaFilled(false);
        bt_buscar.setOpaque(false);
        bt_buscar.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_volver = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_compartir = new javax.swing.JButton();
        bt_submenuverde = new javax.swing.JButton();
        tf_busqueda = new javax.swing.JTextField();
        lb_foto = new javax.swing.JLabel();
        bt_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_contactos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        getContentPane().add(bt_volver);
        bt_volver.setBounds(0, 0, 60, 50);
        getContentPane().add(bt_editar);
        bt_editar.setBounds(223, 0, 50, 50);
        getContentPane().add(bt_compartir);
        bt_compartir.setBounds(270, 0, 50, 50);
        getContentPane().add(bt_submenuverde);
        bt_submenuverde.setBounds(320, 0, 30, 50);

        tf_busqueda.setText("...");
        tf_busqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(tf_busqueda);
        tf_busqueda.setBounds(70, 70, 240, 30);

        lb_foto.setText(".");
        getContentPane().add(lb_foto);
        lb_foto.setBounds(270, 130, 60, 70);

        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_buscar);
        bt_buscar.setBounds(10, 70, 50, 40);

        tb_contactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_contactos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 300, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaapp/imagenes/bg_buscar.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 615);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        // TODO add your handling code here:
        Menu menu1 = new Menu();
        setVisible(false);
        menu1.setVisible(true);
    }//GEN-LAST:event_bt_volverActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_compartir;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_submenuverde;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JTable tb_contactos;
    private javax.swing.JTextField tf_busqueda;
    // End of variables declaration//GEN-END:variables
}
