/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaapp;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anthoro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, 343, 630);
        setLocationRelativeTo(null);
        //OCULTAMIENTO DE BOTONES
        bt_add.setOpaque(false);
        bt_add.setContentAreaFilled(false);
        //bt_add.setBorderPainted(false);
        //bt_add.setFocusPainted(false);
        bt_find.setOpaque(false);
        bt_find.setContentAreaFilled(false);
        bt_sendmsg.setOpaque(false);
        bt_sendmsg.setContentAreaFilled(false);
        bt_call.setOpaque(false);
        bt_call.setContentAreaFilled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_call = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_find = new javax.swing.JButton();
        bt_sendmsg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("menu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        bt_call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_callActionPerformed(evt);
            }
        });
        getContentPane().add(bt_call);
        bt_call.setBounds(200, 430, 110, 110);

        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        getContentPane().add(bt_add);
        bt_add.setBounds(40, 310, 110, 110);

        bt_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_findActionPerformed(evt);
            }
        });
        getContentPane().add(bt_find);
        bt_find.setBounds(200, 310, 110, 110);

        bt_sendmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sendmsgActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sendmsg);
        bt_sendmsg.setBounds(40, 430, 110, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaapp/imagenes/bg_menu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 347, 614);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_callActionPerformed
        // TODO add your handling code here:
        Llamada call1 = new Llamada();
        setVisible(false);
        call1.setVisible(true);
    }//GEN-LAST:event_bt_callActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        Agregar ag1 = new Agregar();
        setVisible(false);
        ag1.setVisible(true);
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_findActionPerformed
        // TODO add your handling code here:
        Buscar bus1 = new Buscar();
        setVisible(false);
        bus1.setVisible(true);
    }//GEN-LAST:event_bt_findActionPerformed

    private void bt_sendmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sendmsgActionPerformed
        // TODO add your handling code here:
        Enviomensaje env1 = new Enviomensaje();
        setVisible(false);
        env1.setVisible(true);
    }//GEN-LAST:event_bt_sendmsgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_call;
    private javax.swing.JButton bt_find;
    private javax.swing.JButton bt_sendmsg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
