/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaapp;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author anthoro
 */
public class Share extends javax.swing.JFrame {

    /**
     * Creates new form Share
     */
    public Share() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, 329, 630);
        setLocationRelativeTo(null);
        //OCULTAMIENTO
        bt_volver.setOpaque(false);
        bt_volver.setContentAreaFilled(false);
        bt_pdf.setOpaque(false);
        bt_pdf.setContentAreaFilled(false);
        bt_messenger.setOpaque(false);
        bt_messenger.setContentAreaFilled(false);
        bt_whatsapp.setOpaque(false);
        bt_whatsapp.setContentAreaFilled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_volver = new javax.swing.JButton();
        bt_whatsapp = new javax.swing.JButton();
        bt_messenger = new javax.swing.JButton();
        bt_pdf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        getContentPane().add(bt_volver);
        bt_volver.setBounds(0, 0, 60, 50);
        getContentPane().add(bt_whatsapp);
        bt_whatsapp.setBounds(20, 430, 220, 70);
        getContentPane().add(bt_messenger);
        bt_messenger.setBounds(20, 310, 220, 70);
        getContentPane().add(bt_pdf);
        bt_pdf.setBounds(20, 200, 220, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaapp/imagenes/bg_share.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 330, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        // TODO add your handling code here:
        Menu menu1 = new Menu();
        setVisible(false);
        menu1.setVisible(true);
    }//GEN-LAST:event_bt_volverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_messenger;
    private javax.swing.JButton bt_pdf;
    private javax.swing.JButton bt_volver;
    private javax.swing.JButton bt_whatsapp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
