/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaapp;

import java.awt.*;

/**
 *
 * @author rayo
 */
public class Submenuazul extends javax.swing.JFrame {

    /**
     * Creates new form Submenuazul
     */
    public Submenuazul() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(1,1, 363,654);
        setLocationRelativeTo(null);
         bt_volver.setOpaque(false);
        bt_volver.setContentAreaFilled(false);
        bt_menuprincipal.setOpaque(false);
        bt_menuprincipal.setContentAreaFilled(false);
        bt_terminaraplicacion.setOpaque(false);
        bt_terminaraplicacion.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_volver = new javax.swing.JButton();
        bt_menuprincipal = new javax.swing.JButton();
        bt_terminaraplicacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        getContentPane().add(bt_volver);
        bt_volver.setBounds(0, 0, 70, 50);
        getContentPane().add(bt_menuprincipal);
        bt_menuprincipal.setBounds(0, 170, 350, 130);
        getContentPane().add(bt_terminaraplicacion);
        bt_terminaraplicacion.setBounds(0, 300, 350, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaapp/imagenes/bg_submenuazul.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 345, 611);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        // TODO add your handling code here:
        Menu menu1 = new Menu();
        setVisible(false);
        menu1.setVisible(true);
    }//GEN-LAST:event_bt_volverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_menuprincipal;
    private javax.swing.JButton bt_terminaraplicacion;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
